import type { LedgerData } from "@/core/models";
import { createInitialLedgerData } from "@/core/state";

export const GOLDEN_LEDGER_FILE_V2_PASSPHRASE =
  "W15-Golden-V2-Fictional-Ledger";

export function createGoldenStorageScenario(): LedgerData {
  return {
    ...createInitialLedgerData(),
    trades: [
      {
        id: "golden-storage-buy-001",
        occurredAt: "2026-08-10T09:00:00Z",
        timePrecision: "second",
        type: "buy",
        assetSymbol: "BTC",
        quantity: "5",
        price: "10",
        totalValue: "50",
        currency: "USDT",
        fee: "0.5",
        feeCurrency: "USDT",
        platform: "Fictional Exchange",
        note: "Fictional first cost lot.",
        rawText: "Fictional golden fixture: buy five BTC at ten USDT.",
        createdAt: "2026-08-10T09:00:00Z",
        updatedAt: "2026-08-10T09:00:00Z",
      },
      {
        id: "golden-storage-buy-002",
        occurredAt: "2026-08-11T09:00:00Z",
        timePrecision: "second",
        type: "buy",
        assetSymbol: "BTC",
        quantity: "7",
        price: "20",
        totalValue: "140",
        currency: "USDT",
        fee: "0.7",
        feeCurrency: "USDT",
        platform: "Fictional Exchange",
        note: "Fictional second cost lot.",
        rawText: "Fictional golden fixture: buy seven BTC at twenty USDT.",
        createdAt: "2026-08-11T09:00:00Z",
        updatedAt: "2026-08-11T09:00:00Z",
      },
      {
        id: "golden-storage-sell-001",
        occurredAt: "2026-08-12T09:00:00Z",
        timePrecision: "second",
        type: "sell",
        assetSymbol: "BTC",
        quantity: "6",
        price: "30",
        totalValue: "180",
        currency: "USDT",
        fee: "0.9",
        feeCurrency: "USDT",
        platform: "Fictional Exchange",
        note: "Fictional sale consuming both cost lots.",
        rawText: "Fictional golden fixture: sell six BTC at thirty USDT.",
        createdAt: "2026-08-12T09:00:00Z",
        updatedAt: "2026-08-12T09:00:00Z",
      },
    ],
    cashEvents: [
      {
        id: "golden-storage-cash-deposit",
        occurredAt: "2026-08-09T09:00:00Z",
        timePrecision: "second",
        type: "deposit",
        currency: "USDT",
        amount: "500",
        note: "Fictional cash funding for the golden fixture.",
        createdAt: "2026-08-09T09:00:00Z",
        updatedAt: "2026-08-09T09:00:00Z",
      },
    ],
    assetTransfers: [
      {
        id: "golden-storage-internal-transfer",
        occurredAt: "2026-08-13T09:00:00Z",
        timePrecision: "second",
        assetSymbol: "BTC",
        quantity: "2",
        category: "internal",
        reason: "internal-move",
        networkFee: "0.1",
        fromLocation: "exchange",
        toLocation: "cold-wallet",
        note: "Fictional transfer retaining BTC in two locations.",
        createdAt: "2026-08-13T09:00:00Z",
        updatedAt: "2026-08-13T09:00:00Z",
      },
    ],
    priceSnapshots: [
      {
        id: "golden-storage-price-btc",
        assetSymbol: "BTC",
        price: "31.25",
        currency: "USDT",
        recordedAt: "2026-08-14T09:00:00Z",
        source: "manual",
        note: "Fictional BTC price for the golden fixture.",
        createdAt: "2026-08-14T09:00:00Z",
        updatedAt: "2026-08-14T09:00:00Z",
      },
    ],
  };
}
