import type { PriceSnapshotDraft } from "@/core/models";

export const PRICE_SNAPSHOT_VALIDATION_ERROR_CODES = {
  INVALID_INPUT: "PRICE_SNAPSHOT_INVALID_INPUT",
  ASSET_NOT_FOUND: "PRICE_SNAPSHOT_ASSET_NOT_FOUND",
  INVALID_DECIMAL: "PRICE_SNAPSHOT_INVALID_DECIMAL",
  VALUE_MUST_BE_POSITIVE: "PRICE_SNAPSHOT_VALUE_MUST_BE_POSITIVE",
  CURRENCY_MISMATCH: "PRICE_SNAPSHOT_CURRENCY_MISMATCH",
  INVALID_SOURCE: "PRICE_SNAPSHOT_INVALID_SOURCE",
  INVALID_BINANCE_PROVENANCE: "PRICE_SNAPSHOT_INVALID_BINANCE_PROVENANCE",
  FUTURE_FACT: "PRICE_SNAPSHOT_FUTURE_FACT",
  UNSUPPORTED_VALUATION_CURRENCY:
    "PRICE_SNAPSHOT_UNSUPPORTED_VALUATION_CURRENCY",
  BINANCE_PROVENANCE_REQUIRED:
    "PRICE_SNAPSHOT_BINANCE_PROVENANCE_REQUIRED",
  NEW_FACT_REQUIRES_USDT: "PRICE_SNAPSHOT_NEW_FACT_REQUIRES_USDT",
} as const;

export type PriceSnapshotValidationField =
  | "input"
  | keyof PriceSnapshotDraft;

export type PriceSnapshotValidationError = {
  code:
    | "PRICE_SNAPSHOT_INVALID_INPUT"
    | "PRICE_SNAPSHOT_ASSET_NOT_FOUND"
    | "PRICE_SNAPSHOT_INVALID_DECIMAL"
    | "PRICE_SNAPSHOT_VALUE_MUST_BE_POSITIVE"
    | "PRICE_SNAPSHOT_CURRENCY_MISMATCH"
    | "PRICE_SNAPSHOT_INVALID_SOURCE"
    | "PRICE_SNAPSHOT_INVALID_BINANCE_PROVENANCE"
    | "PRICE_SNAPSHOT_FUTURE_FACT"
    | "PRICE_SNAPSHOT_UNSUPPORTED_VALUATION_CURRENCY"
    | "PRICE_SNAPSHOT_BINANCE_PROVENANCE_REQUIRED"
    | "PRICE_SNAPSHOT_NEW_FACT_REQUIRES_USDT";
  field: PriceSnapshotValidationField;
  message: string;
};
